version: "3.7"

services:
  api:
    build: 
        context: .
        dockerfile: BankingSystemAPI\Dockerfile
    ports:
      - 5000:80
      - 5001:443
    image: bankingsystemapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=<password>
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro